src/java/recomtac/entities/Client.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recomtac.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author Luis Caamaño
 */
@Entity
@Table(name = "public.\"Client\"")

@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Client.findAll", query = "SELECT c FROM Client c")
    , @NamedQuery(name = "Client.findById", query = "SELECT c FROM Client c WHERE c.id = :id")
    , @NamedQuery(name = "Client.findByName", query = "SELECT c FROM Client c WHERE c.name = :name")
    , @NamedQuery(name = "Client.findByDescription", query = "SELECT c FROM Client c WHERE c.description = :description")
    , @NamedQuery(name = "Client.findByType", query = "SELECT c FROM Client c WHERE c.type = :type")
    , @NamedQuery(name = "Client.findByAddress", query = "SELECT c FROM Client c WHERE c.address = :address")
    , @NamedQuery(name = "Client.findByDatecreated", query = "SELECT c FROM Client c WHERE c.datecreated = :datecreated")
    , @NamedQuery(name = "Client.findByLogin", query = "SELECT c FROM Client c WHERE c.login = :login")})
public class Client implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id")
    private Integer id;
    @Basic(optional = false)
    @Column(name = "name")
    private String name;
    @Basic(optional = false)
    @Column(name = "description")
    private String description;
    @Column(name = "type")
    private String type;
    @Column(name = "address")
    private String address;
    @Column(name = "datecreated")
    private String datecreated;
    @Basic(optional = false)
    @Column(name = "login")
    private String login;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "client")
    private List<JobAgent> jobAgentList;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "client")
    private List<User> userList;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "client")
    private List<LocationStart> locationStartList;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "client")
    private List<LocationEnd> locationEndList;
    @JoinColumn(name = "status", referencedColumnName = "id")
    @ManyToOne
    private ClientStatus status;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "client")
    private List<Job> jobList;

    public Client() {
    }

    public Client(Integer id) {
        this.id = id;
    }

    public Client(Integer id, String name, String description, String login) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.login = login;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getDatecreated() {
        return datecreated;
    }

    public void setDatecreated(String datecreated) {
        this.datecreated = datecreated;
    }

    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    @XmlTransient
    public List<JobAgent> getJobAgentList() {
        return jobAgentList;
    }

    public void setJobAgentList(List<JobAgent> jobAgentList) {
        this.jobAgentList = jobAgentList;
    }

    @XmlTransient
    public List<User> getUserList() {
        return userList;
    }

    public void setUserList(List<User> userList) {
        this.userList = userList;
    }

    @XmlTransient
    public List<LocationStart> getLocationStartList() {
        return locationStartList;
    }

    public void setLocationStartList(List<LocationStart> locationStartList) {
        this.locationStartList = locationStartList;
    }

    @XmlTransient
    public List<LocationEnd> getLocationEndList() {
        return locationEndList;
    }

    public void setLocationEndList(List<LocationEnd> locationEndList) {
        this.locationEndList = locationEndList;
    }

    public ClientStatus getStatus() {
        return status;
    }

    public void setStatus(ClientStatus status) {
        this.status = status;
    }

    @XmlTransient
    public List<Job> getJobList() {
        return jobList;
    }

    public void setJobList(List<Job> jobList) {
        this.jobList = jobList;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Client)) {
            return false;
        }
        Client other = (Client) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "recomtac.entities.Client[ id=" + id + " ]";
    }
    
}

src/java/recomtac/controller/ClientController.java
package recomtac.controller;

import recomtac.entities.Client;
import recomtac.controller.util.JsfUtil;
import recomtac.controller.util.JsfUtil.PersistAction;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@Named("clientController")
@SessionScoped
public class ClientController implements Serializable {

    @EJB
    private recomtac.controller.ClientFacade ejbFacade;
    private List<Client> items = null;
    private Client selected;

    public ClientController() {
    }

    public Client getSelected() {
        return selected;
    }

    public void setSelected(Client selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private ClientFacade getFacade() {
        return ejbFacade;
    }

    public Client prepareCreate() {
        selected = new Client();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("ClientCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("ClientUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("ClientDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Client> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public Client getClient(java.lang.Integer id) {
        return getFacade().find(id);
    }

    public List<Client> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Client> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Client.class)
    public static class ClientControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            ClientController controller = (ClientController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "clientController");
            return controller.getClient(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Client) {
                Client o = (Client) object;
                return getStringKey(o.getId());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Client.class.getName()});
                return null;
            }
        }

    }

}

web/client/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="ClientCreateDlg" widgetVar="ClientCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreateClientTitle}">
            <h:form id="ClientCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{clientController.selected != null}">
                        <p:outputLabel value="#{bundle.CreateClientLabel_id}" for="id" />
                        <p:inputText disabled="true" id="id" value="#{clientController.selected.id}" title="#{bundle.CreateClientTitle_id}" required="true" requiredMessage="#{bundle.CreateClientRequiredMessage_id}"/>
                        <p:outputLabel value="#{bundle.CreateClientLabel_name}" for="name" />
                        <p:inputText id="name" value="#{clientController.selected.name}" title="#{bundle.CreateClientTitle_name}" required="true" requiredMessage="#{bundle.CreateClientRequiredMessage_name}"/>
                        <p:outputLabel value="#{bundle.CreateClientLabel_description}" for="description" />
                        <p:inputText id="description" value="#{clientController.selected.description}" title="#{bundle.CreateClientTitle_description}" required="true" requiredMessage="#{bundle.CreateClientRequiredMessage_description}"/>
                        <p:outputLabel value="#{bundle.CreateClientLabel_type}" for="type" />
                        <p:inputText id="type" value="#{clientController.selected.type}" title="#{bundle.CreateClientTitle_type}" />
                        <p:outputLabel value="#{bundle.CreateClientLabel_address}" for="address" />
                        <p:inputText id="address" value="#{clientController.selected.address}" title="#{bundle.CreateClientTitle_address}" />
                        <p:outputLabel value="#{bundle.CreateClientLabel_datecreated}" for="datecreated" />
                        <p:inputText id="datecreated" value="#{clientController.selected.datecreated}" title="#{bundle.CreateClientTitle_datecreated}" />
                        <p:outputLabel value="#{bundle.CreateClientLabel_login}" for="login" />
                        <p:inputText id="login" value="#{clientController.selected.login}" title="#{bundle.CreateClientTitle_login}" required="true" requiredMessage="#{bundle.CreateClientRequiredMessage_login}"/>
                        <p:outputLabel value="#{bundle.CreateClientLabel_status}" for="status" />
                        <p:selectOneMenu id="status" value="#{clientController.selected.status}" >
                            <f:selectItems value="#{clientStatusController.itemsAvailableSelectOne}"
                                           var="statusItem"
                                           itemLabel="#{statusItem.name}"
                                           itemValue="#{statusItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{clientController.create}" value="#{bundle.Save}" update="display,:ClientListForm:datalist,:growl" oncomplete="handleSubmit(args,'ClientCreateDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="ClientCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/client/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="ClientEditDlg" widgetVar="ClientEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditClientTitle}">
            <h:form id="ClientEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{clientController.selected != null}">
                        <p:outputLabel value="#{bundle.EditClientLabel_id}" for="id" />
                        <p:inputText disabled="true" id="id" value="#{clientController.selected.id}" title="#{bundle.EditClientTitle_id}" required="true" requiredMessage="#{bundle.EditClientRequiredMessage_id}"/>
                        <p:outputLabel value="#{bundle.EditClientLabel_name}" for="name" />
                        <p:inputText id="name" value="#{clientController.selected.name}" title="#{bundle.EditClientTitle_name}" required="true" requiredMessage="#{bundle.EditClientRequiredMessage_name}"/>
                        <p:outputLabel value="#{bundle.EditClientLabel_description}" for="description" />
                        <p:inputText id="description" value="#{clientController.selected.description}" title="#{bundle.EditClientTitle_description}" required="true" requiredMessage="#{bundle.EditClientRequiredMessage_description}"/>
                        <p:outputLabel value="#{bundle.EditClientLabel_type}" for="type" />
                        <p:inputText id="type" value="#{clientController.selected.type}" title="#{bundle.EditClientTitle_type}" />
                        <p:outputLabel value="#{bundle.EditClientLabel_address}" for="address" />
                        <p:inputText id="address" value="#{clientController.selected.address}" title="#{bundle.EditClientTitle_address}" />
                        <p:outputLabel value="#{bundle.EditClientLabel_datecreated}" for="datecreated" />
                        <p:inputText id="datecreated" value="#{clientController.selected.datecreated}" title="#{bundle.EditClientTitle_datecreated}" />
                        <p:outputLabel value="#{bundle.EditClientLabel_login}" for="login" />
                        <p:inputText id="login" value="#{clientController.selected.login}" title="#{bundle.EditClientTitle_login}" required="true" requiredMessage="#{bundle.EditClientRequiredMessage_login}"/>
                        <p:outputLabel value="#{bundle.EditClientLabel_status}" for="status" />
                        <p:selectOneMenu id="status" value="#{clientController.selected.status}" >
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{clientStatusController.itemsAvailableSelectOne}"
                                           var="statusItem"
                                           itemLabel="#{statusItem.name}"
                                           itemValue="#{statusItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{clientController.update}" value="#{bundle.Save}" update="display,:ClientListForm:datalist,:growl" oncomplete="handleSubmit(args, 'ClientEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="ClientEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/client/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle.ListClientTitle}"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <h:form id="ClientListForm">
                <p:panel header="#{bundle.ListClientTitle}">
                    <p:dataTable id="datalist" value="#{clientController.items}" var="item"
                                 selectionMode="single" selection="#{clientController.selected}"
                                 paginator="true"
                                 rowKey="#{item.id}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update="createButton viewButton editButton deleteButton"/>
                        <p:ajax event="rowUnselect" update="createButton viewButton editButton deleteButton"/>

<!--                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListClientTitle_id}"/>
                            </f:facet>
                            <h:outputText value="#{item.id}"/>
                        </p:column>-->
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListClientTitle_name}"/>
                            </f:facet>
                            <h:outputText value="#{item.name}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListClientTitle_description}"/>
                            </f:facet>
                            <h:outputText value="#{item.description}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListClientTitle_type}"/>
                            </f:facet>
                            <h:outputText value="#{item.type}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListClientTitle_address}"/>
                            </f:facet>
                            <h:outputText value="#{item.address}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListClientTitle_datecreated}"/>
                            </f:facet>
                            <h:outputText value="#{item.datecreated}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListClientTitle_login}"/>
                            </f:facet>
                            <h:outputText value="#{item.login}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListClientTitle_status}"/>
                            </f:facet>
                            <h:outputText value="#{item.status.name}"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton id="createButton" icon="ui-icon-plus"   value="#{bundle.Create}" actionListener="#{clientController.prepareCreate}" update=":ClientCreateForm" oncomplete="PF('ClientCreateDialog').show()"/>
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{bundle.View}" update=":ClientViewForm" oncomplete="PF('ClientViewDialog').show()" disabled="#{empty clientController.selected}"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{bundle.Edit}" update=":ClientEditForm" oncomplete="PF('ClientEditDialog').show()" disabled="#{empty clientController.selected}"/>
                            <p:commandButton id="deleteButton" icon="ui-icon-trash"  value="#{bundle.Delete}" actionListener="#{clientController.destroy}" update=":growl,datalist" disabled="#{empty clientController.selected}"/>
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Create.xhtml"/>
            <ui:include src="Edit.xhtml"/>
            <ui:include src="View.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

web/client/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="ClientViewDlg" widgetVar="ClientViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewClientTitle}">
            <h:form id="ClientViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{clientController.selected != null}">
                        <h:outputText value="#{bundle.ViewClientLabel_id}"/>
                        <h:outputText value="#{clientController.selected.id}" title="#{bundle.ViewClientTitle_id}"/>
                        <h:outputText value="#{bundle.ViewClientLabel_name}"/>
                        <h:outputText value="#{clientController.selected.name}" title="#{bundle.ViewClientTitle_name}"/>
                        <h:outputText value="#{bundle.ViewClientLabel_description}"/>
                        <h:outputText value="#{clientController.selected.description}" title="#{bundle.ViewClientTitle_description}"/>
                        <h:outputText value="#{bundle.ViewClientLabel_type}"/>
                        <h:outputText value="#{clientController.selected.type}" title="#{bundle.ViewClientTitle_type}"/>
                        <h:outputText value="#{bundle.ViewClientLabel_address}"/>
                        <h:outputText value="#{clientController.selected.address}" title="#{bundle.ViewClientTitle_address}"/>
                        <h:outputText value="#{bundle.ViewClientLabel_datecreated}"/>
                        <h:outputText value="#{clientController.selected.datecreated}" title="#{bundle.ViewClientTitle_datecreated}"/>
                        <h:outputText value="#{bundle.ViewClientLabel_login}"/>
                        <h:outputText value="#{clientController.selected.login}" title="#{bundle.ViewClientTitle_login}"/>
                        <h:outputText value="#{bundle.ViewClientLabel_status}"/>
                        <h:outputText value="#{clientController.selected.status}" title="#{bundle.ViewClientTitle_status}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="ClientViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>